# Network file mount to share Markdown documents from hashtag-docs
# @see https://docs.platform.sh/configuration/app/storage.html#mounts
shared:
  type: network-storage:1.0
  disk: 128
headlessbrowser:
  type: chrome-headless:73
varnish:
  type: varnish:6.3
  #relationships:
  #  application: "dev:http"
  configuration:
    vcl: !include
      type: string
      path: config.vcl
